# EnGin 项目主配置文件

# Web 服务配置
server:
    port: 8080          # 服务监听的端口
    mode: "release"       # 运行模式：debug (开发模式，带控制台彩色日志) / release (生产模式，只输出 JSON 日志)

database:
  driver: "postgres"    # 驱动，支持 mysql 或 postgres
  host: "127.0.0.1"     # 数据库主机地址
  port: 5432            # 端口号：MySQL 默认 3306，PostgreSQL 默认 5432
  user: "postgres"      # 用户名
  password: "123456"    # 密码
  dbname: "test_db"     # 数据库名

# Zap 日志配置
logger:
    prefix: "myproject"        # 日志前缀
    level: "debug"             # 日志记录级别：debug, info, warn, error
    filename: "./logs/app.log" # 日志输出路径 (会自动创建文件夹)
    max_size: 100              # 单个日志文件最大大小 (单位: MB)
    max_backups: 7             # 最多保留的旧日志文件个数
    max_age: 30                # 旧日志文件最长保留天数 (单位: 天)
    compress: true             # 是否对历史归档日志进行 gzip 压缩